<?php
/**
 * Copyright © 2024 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 * @var Escaper $escaper
 */
?>

<style>
    .pagebuilder-slider {
        /* NOTE: default values */
        --image-width-desktop: 1;
        --image-height-desktop: 1;
    }

    @media (max-width: 767px) {
        .pagebuilder-slider [data-content-type="slide"],
        .pagebuilder-slider .pagebuilder-slide-wrapper {
            aspect-ratio: var(--image-width-mobile, var(--image-width-desktop)) / var(--image-height-mobile, var(--image-height-desktop));
        }
    }

    @media (min-width: 768px) {
        .pagebuilder-slider [data-content-type="slide"],
        .pagebuilder-slider .pagebuilder-slide-wrapper {
            aspect-ratio: var(--image-width-desktop) / var(--image-height-desktop);
        }
    }

    .pagebuilder-slider .pagebuilder-slide-wrapper {
        width: 100%;
        min-height: auto !important;
    }

    .pagebuilder-slider [data-content-type="slide"] > div {
        display: flex;
        justify-content: center;
    }

    .pagebuilder-slider .pagebuilder-overlay {
        min-height: auto !important;
    }
</style>
