<?php
/**
 * Copyright © 2024 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 * @var Escaper $escaper
 */
?>
<style>
    @media (max-width: 639px) {
        .pagebuilder-slider.has-size [data-content-type="slide"],
        .pagebuilder-slider.has-size .pagebuilder-slide-wrapper {
            aspect-ratio: var(
                --image-width-mobile,
                var(
                    --image-width-tablet,
                    var(--image-width-desktop)
                )
            ) / var(
                --image-height-mobile,
                var(
                    --image-height-tablet,
                    var(--image-height-desktop)
                )
            );
        }
    }

    @media (min-width: 640px) and (max-width: 1023px) {
        .pagebuilder-slider.has-size [data-content-type="slide"],
        .pagebuilder-slider.has-size .pagebuilder-slide-wrapper {
            aspect-ratio: var(
                --image-width-tablet,
                var(--image-width-desktop)
            ) / var(
                --image-height-tablet,
                var(--image-height-desktop)
            );
        }
    }

    @media (min-width: 1024px) {
        .pagebuilder-slider.has-size [data-content-type="slide"],
        .pagebuilder-slider.has-size .pagebuilder-slide-wrapper {
            aspect-ratio: var(--image-width-desktop) / var(--image-height-desktop);
        }
    }

    .pagebuilder-slider.has-size {
        min-height: auto !important;
    }

    .pagebuilder-slider.has-size .pagebuilder-slide-wrapper {
        width: 100%;
        min-height: auto !important;
    }

    .pagebuilder-slider.has-size [data-content-type="slide"] > div {
        display: flex;
        justify-content: center;
    }

    .pagebuilder-slider.has-size .pagebuilder-overlay {
        min-height: auto !important;
    }
</style>
