<?php
/**
 * Copyright © 2024 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 * @var Escaper $escaper
 */
?>
<style>
    @media (max-width: 639px) {
        .pagebuilder-slider.has-size-mobile [data-content-type="slide"],
        .pagebuilder-slider.has-size-mobile .pagebuilder-slide-wrapper {
            aspect-ratio: var(--image-width-mobile) / var(--image-height-mobile);
        }

        .pagebuilder-slider.has-size-mobile {
            min-height: auto !important;
        }

        .pagebuilder-slider.has-size-mobile .pagebuilder-slide-wrapper {
            width: 100%;
            min-height: auto !important;
        }

        .pagebuilder-slider.has-size-mobile [data-content-type="slide"] > div {
            display: flex;
            justify-content: center;
        }

        .pagebuilder-slider.has-size-mobile .pagebuilder-overlay {
            min-height: auto !important;
        }
    }

    @media (min-width: 640px) and (max-width: 1023px) {
        .pagebuilder-slider.has-size-tablet [data-content-type="slide"],
        .pagebuilder-slider.has-size-tablet .pagebuilder-slide-wrapper {
            aspect-ratio: var(--image-width-tablet) / var(--image-height-tablet);
        }

        .pagebuilder-slider.has-size-tablet {
            min-height: auto !important;
        }

        .pagebuilder-slider.has-size-tablet .pagebuilder-slide-wrapper {
            width: 100%;
            min-height: auto !important;
        }

        .pagebuilder-slider.has-size-tablet [data-content-type="slide"] > div {
            display: flex;
            justify-content: center;
        }

        .pagebuilder-slider.has-size-tablet .pagebuilder-overlay {
            min-height: auto !important;
        }
    }

    @media (min-width: 1024px) {
        .pagebuilder-slider.has-size-desktop [data-content-type="slide"],
        .pagebuilder-slider.has-size-desktop .pagebuilder-slide-wrapper {
            aspect-ratio: var(--image-width-desktop) / var(--image-height-desktop);
        }

        .pagebuilder-slider.has-size-desktop {
            min-height: auto !important;
        }

        .pagebuilder-slider.has-size-desktop .pagebuilder-slide-wrapper {
            width: 100%;
            min-height: auto !important;
        }

        .pagebuilder-slider.has-size-desktop [data-content-type="slide"] > div {
            display: flex;
            justify-content: center;
        }

        .pagebuilder-slider.has-size-desktop .pagebuilder-overlay {
            min-height: auto !important;
        }
    }
</style>
