<?php
/**
 * Copyright © 2024 Studio Raz. All rights reserved.
 * See LICENSE for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 * @var Escaper $escaper
 */
?>

<script>
    (() => {
        const elements = document.querySelectorAll('.pagebuilder-slider');
        const cssVarSet = {
            desktop: ['--image-width-desktop', '--image-height-desktop'],
            tablet: ['--image-width-tablet', '--image-height-tablet'],
            mobile: ['--image-width-mobile', '--image-height-mobile'],
        };

        Array.from(elements).forEach(element => {
            for (const [breakpointName, cssVars] of Object.entries(cssVarSet)) {
                const hasSize = cssVars.filter(varName => {
                    return getComputedStyle(element).getPropertyValue(varName).trim();
                }).length === cssVars.length;

                if (hasSize) {
                    element.classList.add(`has-size-${breakpointName}`);
                }
            }
        });
    })();
</script>

